export const mockPosts = [
  {
    id: '1',
    author_id: 'user-1',
    author: {
      id: 'user-1',
      username: 'sarahchen',
      name: 'Sarah Chen',
      display_name: 'Sarah Chen',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    },
    title: 'The Future of Design Systems in 2025',
    slug: 'the-future-of-design-systems-in-2025',
    excerpt: 'Exploring how AI and automation are reshaping the way we build design systems. From component generation to automated testing...',
    content:
      'The landscape of design systems is rapidly evolving. Companies are now leveraging AI to generate components, automate testing, and even predict design patterns. This shift is not just about efficiency—it\'s fundamentally changing how designers and developers collaborate. Full content for mock post 1.',
    featured_image_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=800&fit=crop',
    tags: ['design', 'technology', 'ai'],
    status: 'published',
    view_count: 342,
    like_count: 342,
    comment_count: 28,
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    author_id: 'user-2',
    author: {
      id: 'user-2',
      username: 'marcusj',
      name: 'Marcus Johnson',
      display_name: 'Marcus Johnson',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    },
    title: 'Building Scalable React Applications',
    slug: 'building-scalable-react-applications',
    excerpt: "Best practices and patterns I've learned building applications at scale. Including state management, code splitting, and performance optimization...",
    content:
      "After working on projects that handle millions of users, I've identified key patterns that make React applications scalable. Let me share what I've learned about managing complexity. Full content for mock post 2.",
    featured_image_url: 'https://images.unsplash.com/photo-1633356713697-d5daa3b83203?w=1200&h=800&fit=crop',
    tags: ['react', 'web-development', 'performance'],
    status: 'published',
    view_count: 215,
    like_count: 215,
    comment_count: 42,
    published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    author_id: 'user-3',
    author: {
      id: 'user-3',
      username: 'elenrod',
      name: 'Elena Rodriguez',
      display_name: 'Elena Rodriguez',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    },
    title: "Why Accessibility Isn't Optional",
    slug: 'why-accessibility-isnt-optional',
    excerpt: "A compelling case for making accessibility a core principle, not an afterthought. Real stories from users with disabilities...",
    content:
      "Accessibility isn't just about compliance—it's about inclusion. When we design for people with disabilities, we create better products for everyone. Let me share some insights from recent research. Full content for mock post 3.",
    featured_image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=800&fit=crop',
    tags: ['accessibility', 'ux', 'design'],
    status: 'published',
    view_count: 567,
    like_count: 567,
    comment_count: 89,
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]
