export const mockComments = [
  {
    id: '1',
    post_id: '1',
    user_id: 'user-2',
    user: {
      id: 'user-2',
      username: 'alexkim',
      display_name: 'Alex Kim',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    },
    content: 'This is such an insightful perspective! Really appreciate you sharing this.',
    parent_comment_id: null,
    reply_count: 1,
    is_edited: false,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: '1-1',
    post_id: '1',
    user_id: 'user-1',
    user: {
      id: 'user-1',
      username: 'sarahchen',
      display_name: 'Sarah Chen',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    },
    content: 'Thank you, Alex! Would love to hear more about your experience.',
    parent_comment_id: '1',
    reply_count: 0,
    is_edited: false,
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    post_id: '1',
    user_id: 'user-3',
    user: {
      id: 'user-3',
      username: 'jordanlee',
      display_name: 'Jordan Lee',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    },
    content: 'Could you elaborate on the implementation details?',
    parent_comment_id: null,
    reply_count: 0,
    is_edited: false,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
]
